apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
	app: influxdb-service
spec:
  type: LoadBalancer
  ports:
	- ports: 8086
  selector:
	app: influxdb-deployment
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  spec:
	storageClassName: influxdb
	capacity:
	  storage: 2Gi
	accessModes:
	  - ReadWriteMany
	PersistentVolumeClaimPolicy: Retain
	gcePersistentDisk:
	  pdName: pv-kmin-disk
	  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  storageClassName: influxdb
  accessModes:
  - ReadWriteMany
  resources:
	requests:
	  storage: 2Gi
  volumeName: influxdb-pv
---
apiVersion: apps/v1
type: Deployment
metadata:
  name: influxdb-deployment
  labels:
	app: influxdb-deployment
spec:
  replicas: 1
  selector:
	matchLabels:
		app: influxdb-service
  template:
	  metadata:
		name: influxdb-pod
	    labels:
		    app: influxdb-deployment
	  spec:
	    containers:
		    - name: influxdb-deployment
		    image: service_influxdb
		    ports:
			    - containerPort: 8086
		    volumeMounts:
			    - name: influxdb
			    mountPath: /var/lib/influxdb
	    volumes:
		    - name: influxdb
		    persistentVolumeClaim:
			  claimName: influxdb-pv-claim