apiVersion: v1
kind: Service
metadata:
  name: nginx-wordpress
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: secret-volumes
        secret:
          secretName: nginxsecret
      - name: wordpress-volumes
        persistentVolumeClaim:
          claimName: wp-pv-claim
      - name: configmap-volumes
        configMap:
          name: nginxconfigmap
      containers:
      - name: nginxhttps
        image: service-nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volumes
        - mountPath: /etc/nginx/conf.d
          name: configmap-volumes
        - mountPath: /var/www/html/
          name: wordpress-volumes