apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: service-ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30000
        - containerPort: 30001
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password
        volumeMounts:
        - name: ftps-config
          mountPath: /etc/vsftpd
      volumes:
        - name: ftps-config
          configMap:
            name: ftps-config
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftp-data
    port: 20
    targetPort: 20
  - name: ftp-connection
    port: 21
    targetPort: 21
  - name: pftp-data-0
    port: 30000
    targetPort: 30000
  - name: pftp-data-1
    port: 30001
    targetPort: 30001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftps-config
data:
  vsftpd.conf: |
    # ################
    # General Settings
    # ################
    listen=YES
    write_enable=YES
    # ##################
    # Connection Setting
    # ##################
    local_enable=YES
    force_local_data_ssl=YES
    force_local_logins_ssl=YES
    pam_service_name=vsftpd
    ssl_ciphers=HIGH
    ssl_enable=YES
    # ############
    # Mode Setting
    # ############
    port_enable=YES
    connect_from_port_20=YES
    pasv_enable=YES
    seccomp_sandbox=NO
    pasv_address=192.168.99.101
    pasv_min_port=30000
    pasv_max_port=30010
    # ##################
    # Permission Setting
    # ##################
    local_umask=022
    # ################
    # Security Setting
    # ################
    chroot_local_user=YES
    # ############
    # Log Settings
    # ############
    xferlog_enable=YES
    xferlog_std_format=YES
    xferlog_file=/var/log/vsftpd.log
    # ######################
    # Anonymous User Setting
    # ######################
    anonymous_enable=NO
    allow_anon_ssl=NO
    # ###
    # etc
    # ###
    require_ssl_reuse=NO
    validate_cert=YES
    allow_writeable_chroot=YES
    log_ftp_protocol=YES
    rsa_cert_file=/etc/ssl/certs/vsftpd.crt
    rsa_private_key_file=/etc/ssl/private/vsftpd.key