{
 "title": "SERVICES",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "wordpress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "telegraf",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_in_kernelmode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "telegraf" }
     ]
    }
   ]
  },
  {
   "title": "phpmyadmin",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "hierarchical_memory_limit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "phpmyadmin" }
     ]
    }
   ]
  },
  {
   "title": "nginx",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "uptime_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "mysql",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "mysql" }
     ]
    }
   ]
  },
  {
   "title": "influxdb",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "ftps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  }
 ]
}